// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Esercizio15052025.Models;

public partial class EQUIPPINGContext : DbContext
{
    public EQUIPPINGContext(DbContextOptions<EQUIPPINGContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ListPermissionId> ListPermissionIds { get; set; }

    public virtual DbSet<ListVisibilityId> ListVisibilityIds { get; set; }

    public virtual DbSet<PlantComponent> PlantComponents { get; set; }

    public virtual DbSet<Tool> Tools { get; set; }

    public virtual DbSet<ToolCategory> ToolCategories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ListPermissionId>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ListPerm__3214EC0730647C9D");

            entity.ToTable("ListPermissionID");

            entity.HasOne(d => d.User).WithMany(p => p.ListPermissionIds)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ListPermissionID_Users");
        });

        modelBuilder.Entity<ListVisibilityId>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ListPerm__3214EC0750249D5E");

            entity.ToTable("ListVisibilityID");

            entity.HasOne(d => d.User).WithMany(p => p.ListVisibilityIds)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ListVisibilityID_Users");
        });

        modelBuilder.Entity<PlantComponent>(entity =>
        {
            entity.HasKey(e => e.ComponentId).HasName("PK__PlantCom__D79CF04EA745BDF4");

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.PlantComponents)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_PlantComponents_CreatedByUserId_Users");
        });

        modelBuilder.Entity<Tool>(entity =>
        {
            entity.HasKey(e => e.ToolId).HasName("PK__Tools__CC0CEB910C50D77C");

            entity.HasIndex(e => e.Name, "IndexName").IsUnique();

            entity.Property(e => e.CreationDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.Tools)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tools__CategoryI__4D94879B");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Tools)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_Tools_CreatedByUserId_Users");

            entity.HasOne(d => d.PlantComponent).WithMany(p => p.Tools)
                .HasForeignKey(d => d.PlantComponentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tools__PlantComp__4E88ABD4");
        });

        modelBuilder.Entity<ToolCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__ToolCate__19093A0B595910FC");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ToolCategories)
                .HasForeignKey(d => d.CreatedByUserId)
                .HasConstraintName("FK_ToolCategories_CreatedByUserId_Users");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CC88D3232");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E4A01EBB5D").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D1053476A97D69").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("user");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}