// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esercizio15052025.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Role { get; set; }

    public virtual ICollection<ListPermissionId> ListPermissionIds { get; set; } = new List<ListPermissionId>();

    public virtual ICollection<ListVisibilityId> ListVisibilityIds { get; set; } = new List<ListVisibilityId>();

    public virtual ICollection<PlantComponent> PlantComponents { get; set; } = new List<PlantComponent>();

    public virtual ICollection<ToolCategory> ToolCategories { get; set; } = new List<ToolCategory>();

    public virtual ICollection<Tool> Tools { get; set; } = new List<Tool>();
}