// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esercizio15052025.Models;

public partial class PlantComponent
{
    public int ComponentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<Tool> Tools { get; set; } = new List<Tool>();
}