// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esercizio15052025.Models;

public partial class Tool
{
    public int ToolId { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int PlantComponentId { get; set; }

    public DateTime CreationDate { get; set; }

    public int? CreatedByUserId { get; set; }

    public virtual ToolCategory Category { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual PlantComponent PlantComponent { get; set; }
}